language: java

jdk:
  - openjdk8

services:
  - docker

before_script:
  - cd docker/dev
  - docker-compose up -d --build
  - docker ps
  - cd ../..

script:

  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify -Ptest-consumer,test-business sonar:sonar


notifications:
  email: false

addons:
  sonarcloud:
    organization: "kamika-ze"
    token:
      secure: d86c18a0433e50067d9a946bc8c675a4d5e1c120 # encrypted value of your token